# -*- coding: utf-8 -*-
"""IrisKNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1smAuM0ZeD9ptY5eblM0gpxBRT2YMfKrX
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix
import io


# define column names
names = [
  'sepal_length',
  'sepal_width',
  'petal_length',
  'petal_width',
  'class',
]

## load tra'ining data
#drive.mount('/content/gdrive')
#df = pd.read_csv('/content/gdrive/My Drive/Colab Notebooks/iris.data', header=None, names=names)
#df.head(n=
df = pd.read_csv()
df.head(20)

sns.pairplot(df)

# create design matrix X and target vector y
X = np.array(df.iloc[:, 0:4])  # end index is exclusive
y = np.array(df['class'])    # another way of indexing a pandas df

# split into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

# instantiate learning model (k = 3)
knn = KNeighborsClassifier(n_neighbors=3)

# fitting the model
knn.fit(X_train, y_train)

# predict the response
y_pred = knn.predict(X_test)

print(y_pred)

print(y_test)

# evaluate accuracy
print("accuracy: {}".format(accuracy_score(y_test, y_pred)))

# Creates a confusion matrix
cm = confusion_matrix(y_test, y_pred)
# Transform to df for easier plotting
cm_df = pd.DataFrame(cm,
                     index = ['setosa','versicolor','virginica'], 
                     columns = ['setosa','versicolor','virginica'])

sns.heatmap(cm_df, annot=True)
plt.title('Accuracy:{0:.3f}'.format(accuracy_score(y_test, y_pred)))
plt.ylabel('Actual label')
plt.xlabel('Predicted label')
plt.show()

# Nova predicao em producao
X_new = [[6.2,2.75,4.0,0.8]]
knn.predict(X_new)